//user
export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_ALL_USERS = "DELETE_ALL_USERS";


//Admin
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const SET_ADMIN_DETAILS = 'SET_ADMIN_DETAILS';

//form
export const SET_QUESTIONS = "SET_QUESTIONS";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const SET_DOC_NAME = "SET_DOC_NAME";
export const SET_DOC_DESC = "SET_DOC_DESC";
export const RETRIEVE_FORMS ="RETRIEVE_FORMS";
export const DELETE_FORM = "DELETE_FORM";
export const GET_FORM_DETAILS_SUCCESS = 'GET_FORM_DETAILS_SUCCESS';
export const GET_FORM_DETAILS_FAILURE = 'GET_FORM_DETAILS_FAILURE';

//response
export const FETCH_RESPONSES_FAILURE ="FETCH_RESPONSES_FAILURE";
export const FETCH_RESPONSES_SUCCESS ="FETCH_RESPONSES_SUCCESS";
