//user
export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_ALL_USERS = "DELETE_ALL_USERS";


//Admin
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const SET_ADMIN_DETAILS = 'SET_ADMIN_DETAILS';
export const UPDATE_ADMIN_DETAILS = 'UPDATE_ADMIN_DETAILS';
//form
export const SET_QUESTIONS = "SET_QUESTIONS";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const SET_DOC_NAME = "SET_DOC_NAME";
export const SET_DOC_DESC = "SET_DOC_DESC";
export const RETRIEVE_FORMS ="RETRIEVE_FORMS";
export const DELETE_FORM = "DELETE_FORM";
export const GET_FORM_DETAILS_SUCCESS = 'GET_FORM_DETAILS_SUCCESS';
export const GET_FORM_DETAILS_FAILURE = 'GET_FORM_DETAILS_FAILURE';
export const UPDATE_FORM_DETAILS = "UPDATE_FORM_DETAILS";

//response
export const FETCH_RESPONSES_FAILURE ="FETCH_RESPONSES_FAILURE";
export const FETCH_RESPONSES_SUCCESS ="FETCH_RESPONSES_SUCCESS";
export const FETCH_RESPONSES_USER_FAILURE ="FETCH_RESPONSES_USER_FAILURE";
export const FETCH_RESPONSES_USER_SUCCESS ="FETCH_RESPONSES_USER_SUCCESS";

//email
export const SEND_FORM_EMAIL_REQUEST = 'SEND_FORM_EMAIL_REQUEST';
export const SEND_FORM_EMAIL_SUCCESS = 'SEND_FORM_EMAIL_SUCCESS';
export const SEND_FORM_EMAIL_FAILURE = 'SEND_FORM_EMAIL_FAILURE';

//recompense
export const CREATE_RECOMPENSE = "CREATE_RECOMPENSE";
export const RETRIEVE_RECOMPENSES = "RETRIEVE_RECOMPENSES";
export const UPDATE_RECOMPENSE = "UPDATE_RECOMPENSE";
export const DELETE_RECOMPENSE = "DELETE_RECOMPENSE";
export const DELETE_ALL_RECOMPENSES = "DELETE_ALL_RECOMPENSES";